services:
  backend:
    image: nvcr.io/nvidia/rapidsai/base:24.12-cuda12.5-py3.12
    pull_policy: always
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 1g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./environment.yml:/home/rapids/environment.yml
